-- What somebody said happened to an item: `lost` or `retired`, and when they said it.
--
-- Generated by `drizzle-kit generate` against `0005_snapshot.json` — the newest snapshot until this
-- one, three hand-written migrations behind the database — and then cut down. The generator also
-- re-emitted `asset_history.seq`, its unique index and `inventory_categories_ws_order_live_uq`,
-- all three of which `0007` and `0008` already created by hand; an unguarded `CREATE UNIQUE INDEX`
-- for an index that exists is a 42P07 during the module's own migration, which is a host service
-- that never binds its port. They are gone from this file, and `0009_snapshot.json` is the first
-- snapshot since `0005` that describes the table the migrations actually build —
-- `scripts/check-snapshot-drift.mjs` is what keeps that true from here.
--
-- ## Why a column and not a status
--
-- `assets.status` is a derivation: the reconciliation sweep recomputes it from the facts, and a
-- value written into it by hand would be undone the next night. A disposition is a decision, so it
-- is one of the facts — `deriveStatus` reads it first — and lives in a column the sweep never
-- writes. `disposition_at` is when the decision was made, which the panel shows as "lost since".
--
-- ## Append-only, and readable by the image before this one
--
-- Two nullable columns with no default. The 0.4.x image never names them and never selects them,
-- so it reads the table exactly as before; rolling it back needs no dump. `IF NOT EXISTS` on both,
-- because a replay of this folder must change nothing — `migrations.test.ts` applies it twice.

ALTER TABLE "mod_inventory"."assets" ADD COLUMN IF NOT EXISTS "disposition" text;--> statement-breakpoint
ALTER TABLE "mod_inventory"."assets" ADD COLUMN IF NOT EXISTS "disposition_at" timestamp with time zone;
